### ISSUE TITLE
requirements not compatible with latest python/torch/cuda

### ISSUE THREAD

**Issue by olympus-terminal** [voidism/Lookback-Lens#2]
It would be helpful to know which python (and possibly) cuda toolkit versions are necessary for Lookback-Lens, as the requirements are not supported in the latest versions.

e.g., pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement torch==2.0.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torch==2.0.0

update: python 3.11 was able to install the required torch 2.0, but python 3.12 only supports torch 2.2.0 and later.

**Comment by voidism** [comment]
Hi @olympus-terminal 

I was using python 3.9.5 and cuda toolkit 11.7
I will update the README accordingly. Thanks for the suggestion!

**Comment by voidism** [comment]
I just added an [ipython notebook](https://colab.research.google.com/github/voidism/Lookback-Lens/blob/master/lookback_lens_demo.ipynb) for easier reproducing the results! https://github.com/voidism/Lookback-Lens/commit/1320454b0e4c1dc898b393169ded6c07d092fa8c
README.md was updated!
